services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 stripe_project.wsgi:application
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web